# Generated by Django 4.1.4 on 2023-08-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_name_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationnumber', models.CharField(max_length=100)),
                ('locationoffset', models.CharField(max_length=100)),
                ('locationType', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.district')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.province')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.road')),
                ('wardnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.wardnumber')),
            ],
        ),
    ]
