# Generated by Django 4.1.4 on 2023-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_name_generator', '0002_hashedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
