# Generated by Django 4.1.4 on 2023-08-25 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_name_generator', '0003_alter_province_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='roadclass',
        ),
        migrations.AlterField(
            model_name='road',
            name='roadnumber',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='Chowk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.road')),
            ],
        ),
        migrations.AddField(
            model_name='hashedlocation',
            name='chowk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building_name_generator.chowk'),
        ),
    ]
